class Contato {
  const Contato(
      this.nome,
      this.profissao,
      this.endereco,
      this.telefone,
      this.email,
      this.website,
      );

  final String nome;
  final String profissao;
  final String endereco;
  final String telefone;
  final String email;
  final String website;

  static const contatos = [
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
    Contato(
      'Nathalya',
      'Eng. Software',
      'Rua Max Doering',
      '479919871',
      'nathalyajb@hotmail.com',
      'watows.com',
    ),
  ];
}